apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-query-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "siglens.labels" . | nindent 4 }}
data:
  server.yaml: |-
    queryNode: true
    ingestNode: false
    licenseKeyPath: {{ include "siglens-license.name" . }}
    {{ if .Values.logsExporter.enabled }}
    esVersion: "8.9.3"
    {{ else }}
    esVersion: "7.9.3"
    {{ end }}
    {{- toYaml .Values.siglens.configs | nindent 4 }}
    {{ if .Values.etcd.enabled }}
    etcd:
      enabled: true
      seedUrls:
        - http://{{ .Release.Name }}-etcd-headless:2380
    {{ end }}